# Generated by Django 5.1.7 on 2025-04-01 17:21

import ImpulsStranica.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImpulsStranica', '0002_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='file',
            field=models.FileField(upload_to=ImpulsStranica.models.upload_to_user, validators=[ImpulsStranica.models.validate_word_file]),
        ),
    ]
