# Generated by Django 5.1.7 on 2025-04-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImpulsStranica', '0003_alter_work_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
